# Generated by Django 4.0.3 on 2022-04-20 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersapp', '0002_rename_create_order_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Формируется'), (2, 'В обработке'), (3, 'Оплачен'), (4, 'Собирается'), (5, 'Готов'), (6, 'Отменён')], default=1, verbose_name='Статус'),
        ),
    ]
