# Generated by Django 4.0.3 on 2022-05-19 13:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0025_shopuserprofile_tagline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 21, 13, 5, 5, 408863), null=True),
        ),
    ]
